### ISSUE TITLE
DbSeeder.cs Question

### ISSUE THREAD

**Issue by mtmulch** [bharney/PCH#45]
So I finally have this thing up and running locally. I do have one question on the initial database seed. Basically I ran into the issue at line 67 in DbSeeder.cs. If there are no users in the AspNetUsers table you essentially grab the SeedAccount information from appsettings.json and create said user. However, I received an error saying that the username is not a role. I assumed that meant an Identity role for the user system and navigated to the AspNetRoles table to see what I could assign. I decided to just assign myself as a "Member". So essentially I changed the following 
```CSHARP
await _userManager.AddToRoleAsync(_user, _config["SeedAccount:UserName"]);
```
to
```CSHARP
await _userManager.AddToRoleAsync(_user, "Member");
```

Is that suppose to be the intended behavior? 
This is when connecting to a localdb btw.

**Comment by bharney** [comment]
Your correct! It should be a role instead of the config value. I had set this seed method up before I was able to register/create a new user. And it had been the starting point for testing authentication and login. It might be more useful now, to add the seed user to the "Admin" role. Currently there is no way to add an Admin through the UI. Correct though! the `AddToRoleAsync` method should take in the `ApplicationUser` and role(string). Its been a while since I set this up, and I remember running into something like this.

**Comment by mtmulch** [comment]
Makes total sense to me. Your registering that class via dependency injection then when the ShoppingCart component is mounted it calls the Redux "action creator" which basically makes an AJAX to the ShoppingCartController the guest user is assigned there if it doesn't exist. When the response is received you dispatch an action and the state for the component is updated, depending on which action you dispatch.

**Comment by mtmulch** [comment]
My question was answered 👍
